### ISSUE TITLE
Next.js + Flask fails in production

### ISSUE THREAD

**Issue by bernatfortet** [vercel/examples#831]
I'm visiting the url: https://nextjs-flask-starter.vercel.app/ which is your official demo of this [Next.js + flask example](https://vercel.com/templates/next.js/nextjs-flask-starter) and I'm getting an error when going to `https://nextjs-flask-starter.vercel.app/api`

<img width="1468" alt="image" src="https://github.com/vercel/examples/assets/390010/65356c73-1b8f-4cce-a4de-42a42c831b33">

Additionally, would you be so kind to show an example of sub paths? e.g. `/api/echo`

I think @steven-tey created the example

**Comment by benfwalla** [comment]
It appears [Vercel's demo](https://nextjs-fastapi-starter.vercel.app/) doesnt even work if you go to https://nextjs-flask-starter.vercel.app/api/python.

I'm going to try with [the FastAPI Template](https://vercel.com/templates/next.js/nextjs-flask-starter), as at least its demo works, so I can reverse engineer.

**Comment by chrispepper1989** [comment]
has this been resolved? the demo still doesnt work, while annoyingly it works locally

**Comment by JavaScriptJohn** [comment]
Bump

**Comment by trek** [comment]
Resolved by https://github.com/vercel/examples/pull/927 I believe. Please reopen and `@` me if not!

**Comment by robbiecren07** [comment]
@trek The starter is still broken, I ran the "deploy" right from the site https://vercel.com/templates/next.js/nextjs-flask-starter - and the initial build failed. 

I have my own repo based of that starter and I got the deploy/build to work, but the Flask API route does not work (it works locally), still trying to figure out why.

**Comment by 31Carlton7** [comment]
@trek Same thing. I got my configuration to work perfectly fine locally but I keep getting a 405 error when I call the route in production which is weird because the POST route I have configured works fine locally but then all of a sudden it can't find it in prod.

**Comment by julioflima** [comment]
Suffering here with the same disease.
